#############################################################################
# Makefile for building: SpaceFighter
# Generated by qmake (3.0) (Qt 5.1.0) on: ??????? ???? 5 14:52:11 2014
# Project:  SpaceFighter.pro
# Template: app
# Command: /media/fady/Work/Programs/Qt5.1.0/5.1.0/gcc_64/bin/qmake -spec linux-g++ -o Makefile SpaceFighter.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++ -I. -I/home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/include -I/home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/include/AL -I/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include -I/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include -I/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include -I/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/bullet
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/media/fady/Work/Programs/Qt5.1.0/5.1.0/gcc_64
LIBS          = $(SUBLIBS) -lrt -ldl -lpthread /home/fady/Apps/Polycode/Release/Linux/Framework/Core/lib/libPolycore.a /home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/lib/libfreetype.a /home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/lib/liblibvorbisfile.a /home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/lib/liblibvorbis.a /home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/lib/liblibogg.a /home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/lib/libopenal.so /home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/lib/libphysfs.a /home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/lib/libpng15.a /home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/lib/libz.a -lGL -lGLU -lSDL /home/fady/Apps/Polycode/Release/Linux/Framework/Modules/lib/libPolycode2DPhysics.a /home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/lib/libBox2D.a /home/fady/Apps/Polycode/Release/Linux/Framework/Modules/lib/libPolycode3DPhysics.a /home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/lib/libBulletDynamics.a /home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/lib/libBulletCollision.a /home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/lib/libLinearMath.a -lX11 
AR            = ar cqs
RANLIB        = 
QMAKE         = /media/fady/Work/Programs/Qt5.1.0/5.1.0/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		fighter.cpp \
		enemy.cpp \
		game.cpp \
		fireball.cpp \
		explosion.cpp 
OBJECTS       = main.o \
		fighter.o \
		enemy.o \
		game.o \
		fireball.o \
		explosion.o
DIST          = ../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/shell-unix.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/unix.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/linux.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-base.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/qconfig.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_config.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_post.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_pre.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_post.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/warn_on.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exceptions.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/yacc.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/lex.prf \
		SpaceFighter.pro \
		SpaceFighter.pro
QMAKE_TARGET  = SpaceFighter
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = SpaceFighter


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SpaceFighter.pro ../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/shell-unix.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/unix.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/linux.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-base.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/qconfig.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_config.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_post.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_pre.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_post.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/warn_on.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exceptions.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/yacc.prf \
		../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/lex.prf \
		SpaceFighter.pro
	$(QMAKE) -spec linux-g++ -o Makefile SpaceFighter.pro
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_pre.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/shell-unix.conf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/unix.conf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/linux.conf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base.conf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-base.conf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/common/g++-unix.conf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/qconfig.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_v8.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_functions.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/qt_config.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/spec_post.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_pre.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/default_pre.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/resolve_config.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/default_post.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/warn_on.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/wayland-scanner.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/exceptions.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/yacc.prf:
../../../Programs/Qt5.1.0/5.1.0/gcc_64/mkspecs/features/lex.prf:
SpaceFighter.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile SpaceFighter.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/SpaceFighter1.0.0 || mkdir -p .tmp/SpaceFighter1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SpaceFighter1.0.0/ && (cd `dirname .tmp/SpaceFighter1.0.0` && $(TAR) SpaceFighter1.0.0.tar SpaceFighter1.0.0 && $(COMPRESS) SpaceFighter1.0.0.tar) && $(MOVE) `dirname .tmp/SpaceFighter1.0.0`/SpaceFighter1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SpaceFighter1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_qtwayland-client-header_make_all:
compiler_qtwayland-client-header_clean:
compiler_qtwayland-client-code_make_all:
compiler_qtwayland-client-code_clean:
compiler_qtwayland-server-header_make_all:
compiler_qtwayland-server-header_clean:
compiler_qtwayland-server-code_make_all:
compiler_qtwayland-server-code_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp game.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/Polycode.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyString.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyGlobals.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyData.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyObject.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/OSBasics.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyLogger.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEventDispatcher.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEventHandler.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEvent.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyConfig.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyPerlin.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEntity.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMatrix4.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector3.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector2.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyQuaternion.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyColor.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRectangle.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRay.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVertex.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyTimer.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyTween.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyTweenManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCore.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCoreInput.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyInputKeys.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCoreServices.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMaterialManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyImage.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyShader.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyResource.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyThreaded.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyResourceManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyInputEvent.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector4.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyBezierCurve.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyQuaternionCurve.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRenderer.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyLabel.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyFont.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/include/ft2build.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/include/freetype/config/ftheader.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyFontGlyphSheet.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyFontManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyTexture.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMaterial.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyTextMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyFixedShader.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCamera.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyScene.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneLine.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneLight.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySkeleton.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyBone.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyScenePrimitive.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneLabel.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyParticleEmitter.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneRenderTexture.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySound.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/include/AL/al.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/include/AL/alc.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySoundManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneSound.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneImage.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyClient.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyPeer.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySocket.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyServer.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyServerWorld.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneSprite.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneEntityInstance.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolycodeView.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySDLCore.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/Polycode2DPhysics.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/PolyPhysicsScreen.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Box2D.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2Settings.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2CircleShape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2Shape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2BlockAllocator.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2Math.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2Collision.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2PolygonShape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2BroadPhase.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2DynamicTree.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2Distance.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2TimeOfImpact.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2Body.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2Fixture.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2WorldCallbacks.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2TimeStep.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2World.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2StackAllocator.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2ContactManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Contacts/b2Contact.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2DistanceJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2Joint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2FrictionJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2GearJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2LineJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2MouseJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2PulleyJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2WeldJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/PolyPhysicsScreenEntity.h \
		fighter.h \
		fireball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

fighter.o: fighter.cpp fighter.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneSprite.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyGlobals.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyScenePrimitive.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEntity.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyString.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMatrix4.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector3.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector2.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyQuaternion.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyColor.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRectangle.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRay.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVertex.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEventDispatcher.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEventHandler.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEvent.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyShader.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyResource.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/Polycode2DPhysics.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/PolyPhysicsScreen.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyScene.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCore.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCoreInput.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyInputKeys.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCoreServices.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMaterialManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyImage.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyObject.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/OSBasics.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyThreaded.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Box2D.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2Settings.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2CircleShape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2Shape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2BlockAllocator.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2Math.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2Collision.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2PolygonShape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2BroadPhase.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2DynamicTree.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2Distance.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2TimeOfImpact.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2Body.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2Fixture.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2WorldCallbacks.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2TimeStep.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2World.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2StackAllocator.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2ContactManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Contacts/b2Contact.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2DistanceJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2Joint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2FrictionJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2GearJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2LineJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2MouseJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2PulleyJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2WeldJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/PolyPhysicsScreenEntity.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyTimer.h \
		fireball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fighter.o fighter.cpp

enemy.o: enemy.cpp enemy.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneSprite.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyGlobals.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyScenePrimitive.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEntity.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyString.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMatrix4.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector3.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector2.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyQuaternion.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyColor.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRectangle.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRay.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVertex.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEventDispatcher.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEventHandler.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEvent.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyShader.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyResource.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/Polycode2DPhysics.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/PolyPhysicsScreen.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyScene.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCore.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCoreInput.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyInputKeys.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCoreServices.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMaterialManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyImage.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyObject.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/OSBasics.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyThreaded.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Box2D.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2Settings.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2CircleShape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2Shape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2BlockAllocator.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2Math.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2Collision.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2PolygonShape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2BroadPhase.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2DynamicTree.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2Distance.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2TimeOfImpact.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2Body.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2Fixture.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2WorldCallbacks.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2TimeStep.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2World.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2StackAllocator.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2ContactManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Contacts/b2Contact.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2DistanceJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2Joint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2FrictionJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2GearJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2LineJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2MouseJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2PulleyJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2WeldJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/PolyPhysicsScreenEntity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enemy.o enemy.cpp

game.o: game.cpp game.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/Polycode.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyString.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyGlobals.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyData.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyObject.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/OSBasics.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyLogger.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEventDispatcher.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEventHandler.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEvent.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyConfig.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyPerlin.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEntity.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMatrix4.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector3.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector2.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyQuaternion.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyColor.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRectangle.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRay.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVertex.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyTimer.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyTween.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyTweenManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCore.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCoreInput.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyInputKeys.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCoreServices.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMaterialManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyImage.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyShader.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyResource.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyThreaded.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyResourceManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyInputEvent.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector4.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyBezierCurve.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyQuaternionCurve.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRenderer.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyLabel.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyFont.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/include/ft2build.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/include/freetype/config/ftheader.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyFontGlyphSheet.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyFontManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyTexture.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMaterial.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyTextMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyFixedShader.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCamera.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyScene.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneLine.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneLight.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySkeleton.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyBone.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyScenePrimitive.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneLabel.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyParticleEmitter.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneRenderTexture.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySound.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/include/AL/al.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/Dependencies/include/AL/alc.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySoundManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneSound.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneImage.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyClient.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyPeer.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySocket.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyServer.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyServerWorld.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneSprite.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneEntityInstance.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolycodeView.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySDLCore.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/Polycode2DPhysics.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/PolyPhysicsScreen.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Box2D.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2Settings.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2CircleShape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2Shape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2BlockAllocator.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2Math.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2Collision.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2PolygonShape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2BroadPhase.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2DynamicTree.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2Distance.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2TimeOfImpact.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2Body.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2Fixture.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2WorldCallbacks.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2TimeStep.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2World.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2StackAllocator.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2ContactManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Contacts/b2Contact.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2DistanceJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2Joint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2FrictionJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2GearJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2LineJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2MouseJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2PulleyJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2WeldJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/PolyPhysicsScreenEntity.h \
		fighter.h \
		fireball.h \
		enemy.h \
		explosion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

fireball.o: fireball.cpp fireball.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneSprite.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyGlobals.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyScenePrimitive.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEntity.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyString.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMatrix4.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector3.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector2.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyQuaternion.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyColor.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRectangle.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRay.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVertex.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEventDispatcher.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEventHandler.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEvent.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyShader.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyResource.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/Polycode2DPhysics.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/PolyPhysicsScreen.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyScene.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCore.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCoreInput.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyInputKeys.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyCoreServices.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMaterialManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyImage.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyObject.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/OSBasics.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyThreaded.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Box2D.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2Settings.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2CircleShape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2Shape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2BlockAllocator.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2Math.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2Collision.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/Shapes/b2PolygonShape.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2BroadPhase.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2DynamicTree.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2Distance.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Collision/b2TimeOfImpact.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2Body.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2Fixture.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2WorldCallbacks.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2TimeStep.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2World.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Common/b2StackAllocator.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/b2ContactManager.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Contacts/b2Contact.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2DistanceJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2Joint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2FrictionJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2GearJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2LineJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2MouseJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2PrismaticJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2PulleyJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2RevoluteJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/Dependencies/include/Box2D/Dynamics/Joints/b2WeldJoint.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Modules/include/PolyPhysicsScreenEntity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fireball.o fireball.cpp

explosion.o: explosion.cpp explosion.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneSprite.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyGlobals.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyScenePrimitive.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolySceneMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEntity.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyString.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMatrix4.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector3.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVector2.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyQuaternion.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyColor.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRectangle.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyRay.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyVertex.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEventDispatcher.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEventHandler.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyEvent.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyShader.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyResource.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyMesh.h \
		/home/fady/Apps/Polycode/Release/Linux/Framework/Core/include/PolyTimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o explosion.o explosion.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

